In this Colab file you can find a list of the most commonly used NumPy functions and array methods in COMP2211. You will find a documentation and an example of the function.

You will also find many questions scattered throughout this glossary. For most questions, you can obtain the answer by simply printing out the desired properties; we have provided answers for the other ones.

In [ ]:
import numpy as np

#### [array](https://numpy.org/doc/stable/reference/generated/numpy.array.html)

The most basic function creates a NumPy array from a list, tuple, or another NumPy array. Returns a fresh, new array.

In [ ]:
a1 = np.array([1, 5, 7, 2, 6, 4])
print(a1)

a2 = np.array([[1, 5, 7], [2, 6, 4]])
print(a2)

[1 5 7 2 6 4]
[[1 5 7]
 [2 6 4]]


#### Useful properties of a NumPy array

##### shape
The shape of a NumPy array is the dimensions of each rows and columns along each direction.

##### dtype
The type of each element in the NumPy array, for example, int, float, np.uint8 (unsigned 8-bit integer) etc.

In [ ]:
a1 = np.array([1, 5, 7, 2, 6, 4])
print(a1.shape, a1.dtype)

a2 = np.array([[1, 5, 7], [2, 6, 4]])
# Question: what is a2.shape and a2.dtype?

(6,) int64


#### [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

Changes the shape of a NumPy array. When one of the arguments is -1, then NumPy will automatically figure out the dimension for you. Returns a copy of the new array.

In [ ]:
a1 = np.array([1, 5, 7, 2, 6, 4])
# Reshapes to (3,2)
b1 = a1.reshape(3,2)
print(b1)

# This also reshapes the array to (3,2), but NumPy figured out the 3 for you
c1 = a1.reshape(-1,2)
print(c1)

# Another example
a2 = np.array([[1, 5, 7], [2, 6, 4]])
b2 = a2.reshape(6)
print(b2)

# Question: what is the output of a1.reshape(1, -1) and a1.reshape(-1, 1)?

[[1 5]
 [7 2]
 [6 4]]
[[1 5]
 [7 2]
 [6 4]]
[1 5 7 2 6 4]


#### [Transpose](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)

Permutes the axes of a given array and returns the new array. The optional arguments specify the order of the axes to permute the array.

In [ ]:
# Creates an array of shape (24,) filled with entries from 0 to 23 in ascending order
range24 = np.arange(24)

# Reshape the range array into a 6 x 4 grid
a1 = range24.reshape(6, 4)
print(a1)

# When the matrix is 2D, then transpose (without additional arguments) swaps the order of the two axes - like matrix transpose
print(a1.transpose())

# Reshape the (24,) array above into shape (2, 3, 4)
a2 = range24.reshape(2, 3, 4)
print(a2.shape)

# When the matrix is more than 2D, then transpose(a, b, c) gives a new array where its axis 0 is the original axis a, its axis 1 is the original axis b and so on
b2 = a2.transpose(1, 2, 0)
print(b2.shape)

# When the matrix is more than 2D, then transpose (without additional arguments) reverses the order of the axes
c2 = a2.transpose()
print(c2.shape)

# Creates an array filled with 1s with shape (22, 11, 20, 12)
a3 = np.ones((22, 11, 20, 12))
b3 = a3.transpose(1, 3, 0, 2)
# Question: what is the shape of b3?

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]
(2, 3, 4)
(3, 4, 2)
(4, 3, 2)


### Array initialization methods

#### [zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html), [ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

Initialize a NumPy array of zeros (or ones) with a given shape (and data type). The default data type is float.

In [ ]:
# This initializes an array of zeros with shape (4, 5)
a1 = np.zeros((4, 5))
print(a1)

# This initializes an array of zeros with shape (3, 6) and integer data type
a2 = np.zeros((3, 6), dtype = int)
print(a2)

# Question: Initialize a NumPy array of shape (22, 11) with all 1s and integer data type
# Question: Initialize a NumPy array of shape (2211, 22, 11) with all 3s and np.uint8 data type (Hint: start with all 1s and multiply the whole array by 3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


#### [zeros_like](https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html), [ones_like](https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html)
Given a NumPy array, initialize a NumPy array of zeros (or ones) with the same shape and data type as the given array

In [ ]:
a1 = np.array([1, 5, 7, 2, 6, 4])
# This initialize an array of zeros with shape that of a1 (6,) and integer data type
b1 = np.zeros_like(a1)
print(b1)

a2 = np.zeros((3, 6), dtype = int)
# Question: initialize a NumPy array of all 1s with the same shape and data type of a2

[0 0 0 0 0 0]


#### [full](https://numpy.org/doc/stable/reference/generated/numpy.full.html)
Initialize a NumPy array with a given shape (and data type), and fill it with a given value at `fill_value`

In [ ]:
# Initialize a NumPy array of shape (2211, 22, 11) with all 3s and integer data type
a1 = np.full(shape = (2211, 22, 11), fill_value = 3, dtype = int)

# Question: how do you confirm a1 really has the desired shape, data type and value?
# Hint: Read the entries on np.all and np.count_nonzero about array comparisons

#### [arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)
Initialize an 1-dimensional NumPy array with the given range. The arguments works exactly like the `range()` constructor. (aka with start, stop, range)

In [ ]:
a1 = np.arange(20)
print(a1)

a2 = np.arange(1, 17)
print(a2)

a3 = np.arange(2, 95, 7)
print(a3)

# Question: Initialize the following array
#    [[ 0,  1,  2,  3],
#     [ 4,  5,  6,  7],
#     [ 8,  9, 10, 11],
#     [12, 13, 14, 15]]
# using arange and reshape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 2  9 16 23 30 37 44 51 58 65 72 79 86 93]


#### np.random

`np.random` is a module that allows one to make NumPy arrays with random entries. The most commonly used functions from the `np.random` module is `random` and `randint`

#### [random](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html)

Creates an array with a given shape and entries between 0 and 1

#### [randint](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)

Creates an array with a given shape, and entries between `low` (inclusive) and `high` (exclusive)

In [ ]:
# Makes an array with shape (3, 5) and random entries between 0 and 1
a1 = np.random.random((3, 5))
print(a1)

# Makes an array with shape (4, 6) and random integer entries in [0, 1, 2, 3, 4]
a2 = np.random.randint(5, size = (4, 6))
print(a2)

# Makes an array with shape (3, 7) and random integer entries in [1, 2, 3, 4, 5, 6, 7, 8, 9]
a3 = np.random.randint(1, 10, size = (3, 7))
print(a3)

[[0.45966171 0.03335411 0.99689917 0.5600796  0.18238536]
 [0.99267121 0.2317056  0.02742871 0.24941952 0.06370562]
 [0.89403698 0.41290769 0.31135485 0.69691182 0.49680196]]
[[4 1 0 3 1 0]
 [0 0 4 0 2 3]
 [3 0 0 4 4 2]
 [1 4 3 2 0 1]]
[[5 6 9 8 7 8 6]
 [1 4 5 2 8 2 6]
 [5 6 8 4 9 9 5]]


### Intra-array operations

#### [min](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.min.html), [max](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html)

Gets the minimum (or maximum) value of an array. If you specify the "axis" argument, the return value will be a new array with $n-1$ dimension, where we take the minimum (or maximum) value along the specified axis only.

We will discuss about the axis argument below.

In [ ]:
a1 = np.array([1, 5, 7, 2, 6, 4])
# The maximum value in the array is 7, so the output is 7
print(np.max(a1))

a2 = np.array([[1, 5, 7], [2, 6, 4]])
# Refer to the above - we count axes inside out - so (1, 2) is axis 0, and (1, 5, 7) is axis 1
# Take minimum of (1, 2), (5, 6) and (7, 4) and return a NumPy array with these three elements
print(np.min(a2, axis = 0))

# Question: make an array of shape (2,) that consists of the largest element of each row from a2

7
[1 5 4]


#### [The `axis` argument](https://stackoverflow.com/questions/22320534/how-does-the-axis-parameter-from-numpy-work)

When we specify the `axis` argument in an array method, we only apply the method across a specified axis. The returned array has the same shape except that the specified dimension will be missing. If we specify `axis = n`, then we perform the operation along the axis corresponding to `some_aray.shape[n]`.

For instance, if the array `some_array` has shape `(1, 2, 3, 4, 5, 6)` and we perform `np.min(some_array, axis = 3)`, then the result has shape `(1, 2, 3, 5, 6)`.

Intuitively, we "squash" the array along the chosen axis, and perform whatever operations on the numbers that get squashed together.

In [ ]:
# Initialize an array with random entries between 0, 1 and shape (22, 11, 12, 3, 4)
a1 = np.random.random((22, 11, 12, 34, 56))

# Get the minimum values along the 2nd axis
b1 = np.min(a1, axis = 2)
c1 = np.min(b1, axis = 3)

# Question: what is the shape of b1 and c1?

# Uses broadcasting to tile an array
a2 = np.arange(15) + np.zeros((5, 10, 25, 1), dtype = int)

# Question: Describe the array a2. What is its shape? What are its entries?

#### [argmin](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html), [argmax](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html)

Get the index of the minimum (or maximum) value of an array. If you specify the "axis" argument, the return value will be a new array with $n-1$ dimension, where we take the minimum (or maximum) value along the specified axis only.

In [ ]:
a1 = np.array([1, 5, 7, 2, 6, 4])
# The index of the maximum value (7) is 2, so the output is 2
print(a1.argmax())

a2 = np.array([[1, 5, 7], [2, 6, 4]])
# Question: what does np.argmin(a2) return?

# Take minimum of (1, 2), (5, 6) and (7, 4) and return a NumPy array with the indices (along the specified axis) of these three elements
# Index of 1 is 0, index of 5 is 0, and index of 4 is 1, so the output is [0, 0, 1]
print(a2.argmin(axis = 0))

2
[0 0 1]


#### [argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)

In argsort, the first element of the array will be the index of the minimum value of the array; the second element of the array will be the index of the second minimum value, and so on. This has an optional `axis` argument.

In [ ]:
a1 = np.array([1, 5, 7, 2, 6, 4])
# Minimum value (1) is at index 0
# Second minimum value (2) is at index 3
# Third minimum value (4) is at index 5
# ...
print(np.argsort(a1))

a2 = np.array([[1, 5, 7], [2, 6, 4]])
# The axis argument does exactly the same thing as above
print(np.argsort(a2, axis = 0))

# Question: How do we get the index of the second largest element of a1?

# Question: What should a1[np.argsort(a1)] return?

[0 3 5 1 4 2]
[[0 0 1]
 [1 1 0]]


#### [sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html)
Returns the numerical sum of a given NumPy array. This has an optional `axis` argument.

In [ ]:
a1 = np.array([1, 5, 7, 2, 6, 4])
print(np.sum(a1))

a2 = np.array([[1, 5, 7], [2, 6, 4]])
print(np.sum(a2, axis = 1))


a3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Question: What is the output of np.sum(a3)?

25
[13 12]


#### [sin](https://numpy.org/doc/stable/reference/generated/numpy.sin.html), [cos](https://numpy.org/doc/stable/reference/generated/numpy.cos.html), [tan](https://numpy.org/doc/stable/reference/generated/numpy.tan.html), [exp](https://numpy.org/doc/stable/reference/generated/numpy.exp.html), [log](https://numpy.org/doc/stable/reference/generated/numpy.log.html), [sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)

The functions you should have learned in MATH1013. These functions allows array-wide math operations.

In [ ]:
a1 = np.array([1, 4, 9, 16, 25, 36])
b1 = np.sqrt(a1)
print(b1)

a2 = np.arange(20)
# Question (hard): Sort the array a2 according to the sine of their values, in ascending order. Your code should be at most five lines and should not contain any loops.
# Hint: np.argsort might help

[1. 2. 3. 4. 5. 6.]


#### [mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html), [average](https://numpy.org/doc/stable/reference/generated/numpy.average.html)

Computes the numerical average of an array. For all intents and purposes in this course `mean` and `average` behaves identically. This has an optional `axis` argument.

#### [std](https://numpy.org/doc/stable/reference/generated/numpy.std.html)

Computes the standard deviation of an array. This has an optional `axis` argument.

In [ ]:
a1 = np.array([1, 5, 7, 2, 6, 4])

# Computes the numerical average of 1, 5, 7, 2, 6, 4
print(np.mean(a1))

a2 = a1.reshape(3, 2)
# Question: what is the output of print(np.mean(a2, axis = 1))?

# Prints the standard deviation of 1, 5, 7, 2, 6, 4
print(np.std(a1))

4.166666666666667
2.1147629234082532


#### [all](https://numpy.org/doc/stable/reference/generated/numpy.all.html)
Returns True if all elements in a given array is True, and False otherwise. If the elements in an array are numbers, then returns True if all elements are non-zero, and False otherwise.

This function is very useful for array comparison since we can't directly use `==` on two NumPy arrays (This returns another NumPy array)

This has an optional `axis` argument.

In [ ]:
a1 = np.array([1, 5, 7, 2, 6, 4])
a2 = np.array([1, 5, 7, 2, 6, 4])
a3 = np.array([1, 5, 7, 2, 6, 3])
a4 = np.array([0, 4, 6, 1, 5, 3])

# Question: what does a1 == a2 return?

print(np.all(a1 == a2))
print(np.all(a1 == a3))
print(np.all(a1 != a4))

True
False
True


#### [count_nonzero](https://numpy.org/doc/stable/reference/generated/numpy.count_nonzero.html)
Returns an integer which counts the number of `True`s in a NumPy array. If the elements in an array are numbers, then returns an integer that counts the number of non-zero elements

This function is very useful for array comparison since we can't directly use `==` on two NumPy arrays (This returns another NumPy array). In addition, your TA likes this function a bit more since it gives you more control over `np.all`

This has an optional `axis` argument.

In [ ]:
a1 = np.array([1, 5, 7, 2, 6, 4])
a2 = np.array([1, 5, 7, 2, 6, 4])
a3 = np.array([1, 5, 7, 2, 6, 3])
a4 = np.array([0, 4, 6, 1, 5, 3])

print(np.count_nonzero(a1 == a3))

# If we want to perform the "array equal" comparison between a1 and a2 like above, we can do the following:
# We can instead look at a1 != a2, then these two arrays are equal if there are no Trues in a1 != a2
print(np.count_nonzero(a1 != a2) == 0)
print(np.count_nonzero(a1 != a3) == 0)

5
True
False


### Inter-array operations

#### [multiply](https://numpy.org/doc/stable/reference/generated/numpy.multiply.html)

Perform element-wise multiplication between two arrays. For NumPy arrays, this function demonstrates the same behaviour as `a1 * a2`

In [ ]:
a1 = np.array([1, 5, 7, 2, 6, 4])
a2 = np.array([3, 1, 1, 2, 8, 7])

# Performs element-wise multiplication on arrays
print(a1 * a2)
print(np.multiply(a1, a2))

[ 3  5  7  4 48 28]
[ 3  5  7  4 48 28]


#### [dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)

This function essentially performs matrix multiplication between two arrays.

If `a1` and `a2` are both 1D arrays, then `np.dot(a1, a2)` returns the dot product of the vectors `a1` and `a2` (element-wise multiply then sum over all entries)

If `a1` and `a2` are both 2D arrays, then `np.dot(a1, a2)` returns the matrix product of `a1` and `a2`.

If `a1` and `a2` does not satisfy one of the above two cases, then NumPy performs some overloads for the function; you can read about its behaviour [here](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).

In [ ]:
a1 = np.array([1, 5, 7, 2, 6, 4])
a2 = np.array([3, 1, 1, 2, 8, 7])

print(np.dot(a1, a2))
# Question: write some code to confirm that the vector dot product is really "element-wise multiply then sum over all entries".

a3 = np.array([[-1, -5,  0], [ 0, -3,  1], [ 0,  2, -1]])
a4 = np.array([[-2,  5,  0], [ 1,  0,  4], [-4,  3,  0]])
print(np.dot(a3, a4))

95
[[ -3  -5 -20]
 [ -7   3 -12]
 [  6  -3   8]]


#### [concatenate](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)
Merges two or more NumPy arrays along a specific axis. The dimensions of the NumPy arrays must match, except possibly at the specified axis.

The arrays should be provided to the function as a single tuple.

In [ ]:
a1 = np.array([1, 5, 7, 2, 6, 4])
a2 = np.array([6, 7, 8, 11])


# Joins a1 and a2, head to tail
a3 = np.concatenate((a1, a2))
print(a3)


# We provide another demonstration of concatenate, on arrays with higher dimensions
b1 = np.array([[1, 5, 7], [2, 6, 4]])
b2 = np.array([[6, 7], [8, 11]])

# Joins a1 and a2 head to tail along axis 1 (the innermost axis)
b3 = np.concatenate((b1, b2), axis = 1)
print(b3)

[ 1  5  7  2  6  4  6  7  8 11]
[[ 1  5  7  6  7]
 [ 2  6  4  8 11]]


### Answers

In [ ]:
########### Answers ############

### Initialize a NumPy array of shape (22, 11) with all 1s and integer data type
ans = np.ones((22, 11), dtype = int)



### Initialize a NumPy array of shape (2211, 22, 11) with all 3s and np.uint8 data type
ans = np.ones((2211, 22, 11), dtype = np.uint8) * 3



### Initialize a NumPy array of all 1s with the same shape and data type of a2
a2 = np.zeros((3, 6), dtype = int)
ans = np.ones_like(a2, dtype = a2.dtype)



### How do you confirm a1 really has the desired shape, data type and value?
a1 = np.full(shape = (2211, 22, 11), fill_value = 3, dtype = int)
# Make the assertion for shape
assert a1.shape == (2211, 22, 11)
# Make the assertion for data type
assert a1.dtype == int
# Confirm all entries are 3s using np.all
assert np.all(a1 == 3)
# Confirm all entries are 3s using np.count_nonzero
assert np.count_nonzero(a1 != 3) == 0



### Make an array of shape (2,) that consists of the largest element of each row from a2
a2 = np.array([[1, 5, 7], [2, 6, 4]])
ans = np.max(a2, axis = 1)



### Describe the array a2. What is its shape? What are its entries?
a2 = np.arange(15) + np.zeros((5, 10, 25, 1), dtype = int)
# a2 has shape (5, 10, 25, 15). The entries runs through 0 to 14 at the last axis, and they are the same along every other axis

# We can confirm our assertions as follows
# Make the assertion for shape
assert a2.shape == (5, 10, 25, 15)

# Confirm that 0 to 14 really runs through the last axis. First we use reshape to squash every other axis
b2 = a2.reshape(-1, 15)
# Then we use broadcasting with the == operator, and use np.all to confirm that 0 to 14 indeed runs through the last axis for every instance of the last axis
# From the way broadcasting works, the np.arange(15) array is also tiled in such a way we also confirmed that all the entries are the same along every other axis
assert np.all(b2 == np.arange(15))



### How do we get the index of the second largest element of a1?
a1 = np.array([1, 5, 7, 2, 6, 4])
# Second largest element is 6, it has index 4
# We can use np.argsort and get the second last element
ans = np.argsort(a1)[-2]
assert ans == 4



### Initialize the following array
#    [[ 0,  1,  2,  3],
#     [ 4,  5,  6,  7],
#     [ 8,  9, 10, 11],
#     [12, 13, 14, 15]]
# using arange and reshape
d = np.arange(16).reshape((4, 4))



### Sort the array a2 according to the sine of their values, in ascending order.
a2 = np.arange(20)

# First we want to compute the sine of the values in a2
sines = np.sin(a2)

# Then we want to get a way to permute "sines" in such a way that it sorts the elements in "sines"
# This can be done via integer array indexing, and the indices can be obtained precisely by argsort
sorted_idx = np.argsort(sines)

# Here if we print sines[sorted_idx], the integer array indexing will permute "sines" in such a way such that it will be sorted
# We can now use this sorted_idx array to permute a2 to get the desired array
result = a2[sorted_idx]

# Your job: print `result` and `sines[sorted_idx]` to confirm our assertions above



### Write some code to confirm that the vector dot product is really "element-wise multiply then sum over all entries".
a1 = np.array([1, 5, 7, 2, 6, 4])
a2 = np.array([3, 1, 1, 2, 8, 7])
dot = np.dot(a1, a2)
mul_then_sum = np.sum(a1 * a2)
assert dot == mul_then_sum



# Oh btw, the assert keyword is basically "if" on steroids - it raises an error and stops program execution if the expression after the keyword evaluates to "False"
# Here you go
assert 1 + 1 == 3

AssertionError: ignored